### ISSUE TITLE
alignBits shouldn't be hard-coded to 12

### ISSUE THREAD

**Issue by messense** [randall77/makefat#3]
https://github.com/tpoechtrager/cctools-port/blob/ae9675d50dae4e77d2b09f6d27daa356419de2de/cctools/misc/lipo.c#L1949-L1970

The fat binary `makefat` produces currently does not work on arm64 macOS (gets killed).

**Comment by randall77** [comment]
What alignment does arm64 require?

**Comment by messense** [comment]
@randall77 1 << 14 according to lipo

**Comment by messense** [comment]
Sorry I mean 1 << 14

**Comment by messense** [comment]
https://opensource.apple.com/source/cctools/cctools-949.0.1/libstuff/arch.c.auto.html

See the `cpu_entries` table.

**Comment by randall77** [comment]
Fixed.
