### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by quackduck** [randall77/makefat#4]
I'd like to use this utility. Could you add some documentation, perhaps on the README, for how to use this? Thanks!

**Comment by randall77** [comment]
There's a one-liner in the code:
```
// makefat <output file> <input file 1> <input file 2> ...
```
Happy to put it elsewhere as well. In the README? A `-help` command-line option?

**Comment by quackduck** [comment]
Both would greatly help normal users :)

**Comment by quackduck** [comment]
Are the input files already built executables or go source files? Which architectures does it make a fat file for?

**Comment by randall77** [comment]
They are executables. It makes a fat file for whatever architectures those executables are built for.

**Comment by quackduck** [comment]
Could you make it so that one could specify architectures and this utility would take in a single Go file and output a fat file? I'd love to work on this.

**Comment by quackduck** [comment]
We could even use some code from https://github.com/randall77/makefat/blob/master/makefat_test.go

**Comment by randall77** [comment]
The point of this tool is to take *any* executable, it doesn't have to be Go.
The tool you describe sounds interesting, but it isn't this one.

**Comment by quackduck** [comment]
I thought you'd made this for the golang proposal. Can I fork this and make the tool I describe?

**Comment by randall77** [comment]
Fork away!

**Comment by networkimprov** [comment]
@quackduck maybe all you need is a shell script:
https://github.com/randall77/makefat/pull/1/files
